let shopItemsData = [
  {
    id: "anything1",
    name: "casual pant",
    price: 45,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img1.webp",
  },
  {
    id: "anything2",
    name: "Office Pant",
    price: 75,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img9.webp",
  },
  {
    id: "anything3",
    name: "School Pant",
    price: 145,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img3.webp",
  },
  {
    id: "anything4",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img6.jpg",
  },
  {
    id: "anything5",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img2.webp",
  },
  {
    id: "anything6",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img4.jpeg",
  },
  {
    id: "anything7",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img7.jpg",
  },
  {
    id: "anything8",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img8.webp",
  },
  {
    id: "anything9",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img9.webp",
  },
  {
    id: "anything10",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img10.jpg",
  },
  {
    id: "anything11",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img11.webp",
  },
  {
    id: "anything12",
    name: "College Pant",
    price: 100,
    desc: "lorem ipsam dolor sit amet consectetur adipisicing.",
    img: "images/img12.webp",
  },
];
